In [2]:
import pandas as pd

In [3]:
poolstate_data = pd.read_csv("graph.csv")
poolstate_data.iloc[1:, 1:]

,periodStartUnix,liquidity,high,low,close,feeGrowthGlobal0X128,feeGrowthGlobal1X128,open,pool.totalValueLockedUSD,pool.totalValueLockedToken1,pool.totalValueLockedToken0,pool.token0.decimals,pool.token1.decimals
1,1.620252e+09,3.450731e+13,3402.729189,3402.729189,3402.729189,0.000000e+00,1.725704e+37,3402.729189,3.875055e+08,80904.320959,2.214553e+08,6.0,18.0
2,1.620256e+09,3.990727e+15,3525.673098,3402.729189,3496.203173,1.777954e+29,1.819374e+37,3402.729189,3.875055e+08,80904.320959,2.214553e+08,6.0,18.0
3,1.620259e+09,8.819118e+15,3542.608114,3480.198579,3480.198579,2.692501e+29,4.470077e+37,3519.716693,3.875055e+08,80904.320959,2.214553e+08,6.0,18.0
4,1.620263e+09,9.911501e+15,3503.486877,3454.734986,3503.486877,4.132894e+29,1.107871e+38,3467.204859,3.875055e+08,80904.320959,2.214553e+08,6.0,18.0
5,1.620266e+09,9.914570e+15,3497.480496,3462.319577,3487.077997,5.510666e+29,1.392612e+38,3497.480496,3.875055e+08,80904.320959,2.214553e+08,6.0,18.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
22130,1.699916e+09,2.232597e+19,2068.675489,2052.231398,2055.270282,2.486088e+33,1.206110e+42,2059.458204,3.875058e+08,80851.706107,2.215636e+08,6.0,18.0
22131,1.699920e+09,2.187154e+19,2056.633607,2023.861278,2033.599609,2.486187e+33,1.206179e+42,2055.309859,3.875058e+08,80851.706107,2.215636e+08,6.0,18.0
22132,1.699924e+09,2.187712e+19,2049.347559,2034.120673,2043.966018,2.486237e+33,1.206194e+42,2034.469908,3.875058e+08,80851.706107,2.215636e+08,6.0,18.0
22133,1.699927e+09,2.229973e+19,2055.457336,2043.929201,2053.193492,2.486268e+33,1.206200e+42,2043.929201,3.875058e+08,80851.706107,2.215636e+08,6.0,18.0
22134,1.699931e+09,2.230454e+19,2057.591351,2053.164591,2056.275151,2.486280e+33,1.206203e+42,2053.164591,3.875058e+08,80851.706107,2.215636e+08,6.0,18.0

In [10]:
important_sheets_anton = pd.read_csv("important_sheets.csv")
important_sheets_anton.head(20)

,date,close,pair_value,total_value,hold_value_compare,hold_strategy_value,amount0,amount1,cumulative_feeV,IL_change,impermanent_loss
0,2022-01-01,3768.746497,10109.720625,10096.963803,10110.375917,10227.884911,5209.044223,1.300347,1.783178,-0.655292,-0.655292
1,2022-01-02,3829.292485,10188.016702,10176.511492,10189.961249,10392.198800,5255.151732,1.288192,3.034790,-1.289255,-1.944547
2,2022-01-03,3764.599189,10104.334010,10093.677582,10104.924443,10216.629659,5205.578460,1.301269,3.883571,1.354115,-0.590432
3,2022-01-04,3788.184268,10134.973206,10125.397224,10135.926106,10280.636477,5244.288257,1.291037,4.964018,-0.362468,-0.952900
4,2022-01-05,3541.813698,9810.119519,9803.762078,9812.081632,9612.018985,5046.228293,1.345043,8.182559,-1.009214,-1.962114
5,2022-01-06,3406.220919,9626.245358,9624.730479,9633.850229,9244.037921,4974.245625,1.365736,13.025121,-5.642757,-7.604871
6,2022-01-07,3195.815731,9332.970262,9341.219338,9357.280843,8673.025769,4789.627060,1.421654,22.789076,-16.705709,-24.310580
7,2022-01-08,3080.272709,9167.691642,9178.966670,9205.404061,8359.457125,4742.046947,1.436770,25.815028,-13.401839,-37.712419
8,2022-01-09,3149.511728,9267.131350,9279.452615,9296.416042,8547.362763,4788.451182,1.422024,26.861265,8.427726,-29.284693
9,2022-01-10,3082.084998,9170.206058,9185.090844,9207.786245,8364.375442,4700.079005,1.450358,29.424786,-8.295495,-37.580187
10,2022-01-11,3237.903021,9392.398925,9408.331218,9412.602939,8787.245169,4831.405173,1.408626,30.472294,17.376173,-20.204014
11,2022-01-12,3369.950266,9576.343718,9593.177442,9586.173875,9145.604115,4926.231133,1.379876,31.373724,10.373857,-9.830157
12,2022-01-13,3238.783836,9393.649206,9411.293757,9413.760736,8789.635586,4841.803817,1.405418,32.184551,-10.281373,-20.111530
13,2022-01-14,3310.633169,9494.198428,9512.846921,9508.203873,8984.625276,4893.190291,1.389767,33.188493,6.106085,-14.005445
14,2022-01-15,3330.224158,9521.419811,9540.597478,9533.955460,9037.792655,4909.462759,1.384879,33.717668,1.469795,-12.535650
15,2022-01-16,3349.643321,9548.303354,9568.039115,9559.481191,9090.493723,4917.469666,1.382486,34.275761,1.357813,-11.177837
16,2022-01-17,3212.353675,9356.396876,9377.059751,9379.019323,8717.907587,4799.795766,1.418462,35.202874,-11.444610,-22.622447
17,2022-01-18,3162.330510,9285.367121,9307.215903,9313.265831,8582.151262,4789.861226,1.421580,36.388782,-5.276262,-27.898709
18,2022-01-19,3089.237312,9180.653418,9203.583176,9217.187682,8383.785886,4749.963994,1.434234,37.469758,-8.635555,-36.534264
19,2022-01-20,3004.126943,9057.107719,9081.281751,9105.313432,8152.807479,4698.374770,1.450915,38.714032,-11.671449,-48.205713